=begin
#Elastic Email REST API

#This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://app.elasticemail.com/marketing/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>

The version of the OpenAPI document: 4.0.0
Contact: support@elasticemail.com
Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'spec_helper'
require 'json'

# Unit tests for ElasticEmail::CampaignsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CampaignsApi' do
  before do
    # run before each test
    @api_instance = ElasticEmail::CampaignsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CampaignsApi' do
    it 'should create an instance of CampaignsApi' do
      expect(@api_instance).to be_instance_of(ElasticEmail::CampaignsApi)
    end
  end

  # unit tests for campaigns_by_name_delete
  # Delete Campaign
  # Delete the specific campaign.  This does not cancel in progress email, see Cancel In Progress. Required Access Level: ModifyCampaigns
  # @param name Name of Campaign to delete
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'campaigns_by_name_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for campaigns_by_name_get
  # Load Campaign
  # Returns the specified campaign details. Required Access Level: ViewCampaigns
  # @param name Name of Campaign to get
  # @param [Hash] opts the optional parameters
  # @return [Campaign]
  describe 'campaigns_by_name_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for campaigns_by_name_pause_put
  # Pause Campaign
  # Pauses the specific campaign, cancelling emails that are waiting to be sent. Required Access Level: ModifyCampaigns
  # @param name Name of Campaign to pause
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'campaigns_by_name_pause_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for campaigns_by_name_put
  # Update Campaign
  # Updates a previously added campaign.  Only Active and Paused campaigns can be updated. Required Access Level: ModifyCampaigns
  # @param name Name of Campaign to update
  # @param campaign JSON representation of a campaign
  # @param [Hash] opts the optional parameters
  # @return [Campaign]
  describe 'campaigns_by_name_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for campaigns_get
  # Load Campaigns
  # Returns a list all of your campaigns. Limited to 1000 results. Required Access Level: ViewCampaigns
  # @param [Hash] opts the optional parameters
  # @option opts [String] :search Text fragment used for searching in Campaign name (using the &#39;contains&#39; rule)
  # @option opts [Integer] :offset How many items should be returned ahead.
  # @option opts [Integer] :limit Maximum number of returned items.
  # @return [Array<Campaign>]
  describe 'campaigns_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for campaigns_post
  # Add Campaign
  # Add a campaign for processing. Required Access Level: ModifyCampaigns
  # @param campaign JSON representation of a campaign
  # @param [Hash] opts the optional parameters
  # @return [Campaign]
  describe 'campaigns_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
