=begin
#Elastic Email REST API

#This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    To start using this API, you will need your Access Token (available <a href=\"https://elasticemail.com/account#/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    This is the documentation for REST API. If you’d like to read our legacy documentation regarding Web API v2 click <a href=\"https://api.elasticemail.com/public/help\">here</a>.

The version of the OpenAPI document: 4.0.0
Contact: support@elasticemail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for ElasticEmail::FilesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FilesApi' do
  before do
    # run before each test
    @api_instance = ElasticEmail::FilesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FilesApi' do
    it 'should create an instance of FilesApi' do
      expect(@api_instance).to be_instance_of(ElasticEmail::FilesApi)
    end
  end

  # unit tests for files_by_name_delete
  # Delete File
  # Permanently deletes the file from your Account. Required Access Level: ModifyFiles
  # @param name Name of your file including extension.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'files_by_name_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for files_by_name_get
  # Download File
  # Gets content of the specified File. Required Access Level: ViewFiles
  # @param name Name of your file including extension.
  # @param [Hash] opts the optional parameters
  # @return [File]
  describe 'files_by_name_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for files_by_name_info_get
  # Load File Details
  # Returns the specified File&#39;s details. Required Access Level: ViewFiles
  # @param name Name of your file including extension.
  # @param [Hash] opts the optional parameters
  # @return [FileInfo]
  describe 'files_by_name_info_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for files_get
  # List Files
  # Returns a list of all your available files. Required Access Level: ViewFiles
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Maximum number of returned items.
  # @option opts [Integer] :offset How many items should be returned ahead.
  # @return [Array<FileInfo>]
  describe 'files_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for files_post
  # Upload File
  # Uploads selected file to the server. Required Access Level: ModifyFiles
  # @param file_payload 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :expires_after_days After how many days should the file be deleted.
  # @return [FileInfo]
  describe 'files_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
