=begin
#Elastic Email REST API

#This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://app.elasticemail.com/marketing/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>

The version of the OpenAPI document: 4.0.0
Contact: support@elasticemail.com
Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'spec_helper'
require 'json'

# Unit tests for ElasticEmail::StatisticsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'StatisticsApi' do
  before do
    # run before each test
    @api_instance = ElasticEmail::StatisticsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StatisticsApi' do
    it 'should create an instance of StatisticsApi' do
      expect(@api_instance).to be_instance_of(ElasticEmail::StatisticsApi)
    end
  end

  # unit tests for statistics_campaigns_by_name_get
  # Load Campaign Stats
  # Retrieve stats of an existing campaign. Required Access Level: ViewChannels
  # @param name The name of the campaign to get.
  # @param [Hash] opts the optional parameters
  # @return [ChannelLogStatusSummary]
  describe 'statistics_campaigns_by_name_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for statistics_campaigns_get
  # Load Campaigns Stats
  # Returns a list of your Campaigns&#39; stats. Required Access Level: ViewChannels
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Maximum number of returned items.
  # @option opts [Integer] :offset How many items should be returned ahead.
  # @return [Array<ChannelLogStatusSummary>]
  describe 'statistics_campaigns_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for statistics_channels_by_name_get
  # Load Channel Stats
  # Retrieve an existing channel stats. Required Access Level: ViewChannels
  # @param name The name of the channel to get.
  # @param [Hash] opts the optional parameters
  # @return [ChannelLogStatusSummary]
  describe 'statistics_channels_by_name_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for statistics_channels_get
  # Load Channels Stats
  # Returns a list of your Channels&#39; stats. Required Access Level: ViewChannels
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Maximum number of returned items.
  # @option opts [Integer] :offset How many items should be returned ahead.
  # @return [Array<ChannelLogStatusSummary>]
  describe 'statistics_channels_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for statistics_get
  # Load Statistics
  # Returns basic statistics. Required Access Level: ViewReports
  # @param from Starting date for search in YYYY-MM-DDThh:mm:ss format.
  # @param [Hash] opts the optional parameters
  # @option opts [Time] :to Ending date for search in YYYY-MM-DDThh:mm:ss format.
  # @return [LogStatusSummary]
  describe 'statistics_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
