=begin
#Elastic Email REST API

#This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://app.elasticemail.com/marketing/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>

The version of the OpenAPI document: 4.0.0
Contact: support@elasticemail.com
Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'date'
require 'time'

module ElasticEmail
  class ContactSource
    DELIVERY_API = "DeliveryApi".freeze
    MANUAL_INPUT = "ManualInput".freeze
    FILE_UPLOAD = "FileUpload".freeze
    WEB_FORM = "WebForm".freeze
    CONTACT_API = "ContactApi".freeze
    VERIFICATION_API = "VerificationApi".freeze
    FILE_VERIFICATION_API = "FileVerificationApi".freeze

    def self.all_vars
      @all_vars ||= [DELIVERY_API, MANUAL_INPUT, FILE_UPLOAD, WEB_FORM, CONTACT_API, VERIFICATION_API, FILE_VERIFICATION_API].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ContactSource.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ContactSource"
    end
  end
end
