=begin
#Elastic Email REST API

#This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://elasticemail.com/account#/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    This is the documentation for REST API. If you’d like to read our legacy documentation regarding Web API v2 click <a target=\"_blank\" href=\"https://api.elasticemail.com/public/help\">here</a>.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>

The version of the OpenAPI document: 4.0.0
Contact: support@elasticemail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'date'
require 'time'

module ElasticEmail
  class MessageCategory
    UNKNOWN = "Unknown".freeze
    IGNORE = "Ignore".freeze
    SPAM = "Spam".freeze
    BLACK_LISTED = "BlackListed".freeze
    NO_MAILBOX = "NoMailbox".freeze
    GREY_LISTED = "GreyListed".freeze
    THROTTLED = "Throttled".freeze
    TIMEOUT = "Timeout".freeze
    CONNECTION_PROBLEM = "ConnectionProblem".freeze
    SPF_PROBLEM = "SPFProblem".freeze
    ACCOUNT_PROBLEM = "AccountProblem".freeze
    DNS_PROBLEM = "DNSProblem".freeze
    NOT_DELIVERED_CANCELLED = "NotDeliveredCancelled".freeze
    CODE_ERROR = "CodeError".freeze
    MANUAL_CANCEL = "ManualCancel".freeze
    CONNECTION_TERMINATED = "ConnectionTerminated".freeze
    NOT_DELIVERED = "NotDelivered".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = MessageCategory.constants.select { |c| MessageCategory::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #MessageCategory" if constantValues.empty?
      value
    end
  end
end
